name: 'Radar Pointcloud Reconstruction'
device: 'cuda'

pointcloud_model: 
    arch: 'MDM'
    max_pc_len: 128
    dropout: 0.0
    in_channels: 6
    out_channels: 6
    predict_velocity: True

condition_model:
    arch: 'EncoderUNetModelNoTime'
    apply: True
    resize_ratio: 3.0

training:
    batch_size: 1
    save_name: 'mdm_velocity_128'
    save_ckpt: '/data/mint/RadarPC/model_logs/test_velocity/'
    visualization: '/data/mint/RadarPC/visualize_logs/test_velocity/'
    save_interval: 10000
    save_ema_interval: 10000
    sampling_interval: 2500
    single_sample_training: True
    single_sample_training_expand: 256
    lr: 0.0001

dataset:
    sample_token: 'first_sample_token'

logging:
    log_interval: 2
    visualize_log_interval: 500
    wandb_logger:
        run_name: 'mdm_velocity_128'
        tags: ['ManTruck']